source/Reloaded.Mod.Launcher.Lib/Utility/ProcessExtensions.cs

* Silently launches cmd for OpenFolder/OpenFileWIthDefaultProgram
* Makes the brief CMD window pop up when a user 'open folder' 's  a mod or launches the help links not appear

Updated: Silent cmd launch for OpenFolder/OpenFileWithDefaultProgram

---

source/Reloaded.Mod.Launcher/Assets/Languages/es-419.xaml

- Revamped the entire Spanish translation. As it was before, it was a mix of diferent dialects, ways to address the user and loaned translations.
- Right now the es-ES translation uses Castilian Spanish for its texts (as the extension says). I have also done a base for a Latin American Spanish translation (the so-called "Neutral", es-419) and did whatever few things I know they do for neutralization, but the main reason the file was made is so any future Latin American translators can fine-tune it and use that file, making sure both versions of Spanish can coexist.
- Added translations for all the missing strings up until today.

Revamp of the Spanish translation + futureproofing it

---

source/Reloaded.Mod.Template/templates/configurable/.github/workflows/reloaded.yml
source/Reloaded.Mod.Template/templates/configurable/Reloaded.Checks.targets
source/Reloaded.Mod.Template/templates/configurable/Reloaded.Mod.Template.csproj

I had installed Reloaded-II manually which I made it not set an environment variable RELOADEDIIMODS. Because of this, when building a mod created from the template, it was copying the output to my drive root and wondering what was wrong 🙃
This PR adds a check to the csproj template to see if the environment variable is set before building and throws an error if it's not set.

Add environment variable check to mod template

---

source/Reloaded.Mod.Launcher.Lib/Models/Model/Dialog/ObservablePackItem.cs
source/Reloaded.Mod.Loader.Update/Packs/AutoPackCreator.cs
source/Reloaded.Mod.Loader.Update/Packs/ReloadedPack.cs
source/Reloaded.Mod.Loader.Update/Packs/ReloadedPackItem.cs
source/Reloaded.Mod.Loader.Update/Packs/ReloadedPackItemBuilder.cs

Previously if a repo uses the multirelease scheme, then the test mod pack feature would fail due to defaulting to the RMFN for the default repo. This change adds this field onto the mod pack item and uses that for configuring the download location.
Reproduction steps for the bug:
Setup a github release with custom release metadata filename
Configure mod to use this release filename
Add mod to mod pack
Use the test mod pack button.
Result: A warning pops up claiming that update support isn't setup correctly or a release is missing because Reloaded-II is using `Sewer56.Update.ReleaseMetadata.json` by default.

Add ReleaseMetadataFileName to mod pack item

---

source/Reloaded.Mod.Interfaces/Reloaded.Mod.Interfaces.csproj
source/Reloaded.Mod.Template/templates/configurable/Reloaded.Mod.Template.csproj
source/Testing/Mods/TestModControlParams/TestModControlParams.csproj

Fixes an issue where new projects using the latest template canont use the new control params since the latest release didn't update the Interfaces.dll
I think this should be enough, but I'm not exactly sure how to test with the current release process. It might be worth doing a quick bug fix with this update ^^; Sorry for the trouble. I think you'll also need to publish the Interface mod to nuget, as the test cases are failing without it on nuget.

Update Reloaded.Mod.Interfaces version number

---

source/Reloaded.Mod.Template/templates/configurable/Config.cs

The template fails to compile without this reference for the new Control fields.

Add missing using in template

---

source/Reloaded.Mod.Launcher.Lib/Utility/ApplicationInjector.cs

Sorry this took so long.
Finally got around to making the simple change and testing it.
Tests:
Made a simple mod which has a 40s delay in loading artificially.
Before change: Message would appear, but game would still load before message disappeared by pressing OK.
After change: Message appears and game doesn't start until OK has been pressed.

Change exception handler to syncronous call

---

source/Reloaded.Mod.Interfaces/Structs/ControlAttribute.cs
source/Reloaded.Mod.Launcher/Controls/PropertyGridEx.cs
source/Testing/Mods/TestModControlParams/Config.cs

Previously for sliders with `double` data type, if you displayed the label it would fluctuate in size wildly because it would show the full un-formatted value.
I have added an extra option so that you can provide a format string.
This makes them much more stable:
I also tried to make the tooltips a bit nicer by adding a delay to the display, but it didn't really seem to do anything. It's a bit annoying IMO having them over the cursor the whole time while you are trying to drag it as you can't see what the value is while dragging. If you have any suggestions on this I'd appreciate it. I tried a few things but nothing stuck...

Add text format attribute for mod configs

---

source/Reloaded.Mod.Loader/Utilities/Steam/SteamHook.cs

Unreal Engine games have the steam api dll in a different folder from the game's exe so Steam Hook didn't work. This pr makes Reloaded attempt to search in the correct place for UE games, letting steam hook work with them. 
As far as I can tell the folder structure is always consistent for UE games so this should work with any (hopefully I'm correct :D)

Make steam hook work with Unreal Engine games

---

source/Reloaded.Mod.Launcher.Lib/Usings.cs
source/Reloaded.Mod.Launcher/Misc/Imaging.cs
source/Reloaded.Mod.Launcher/Pages/BaseSubpages/ApplicationSubPages/AppSummaryPage.xaml
source/Reloaded.Mod.Launcher/Pages/BaseSubpages/ManageModsPage.xaml
source/Reloaded.Mod.Launcher/Reloaded.Mod.Launcher.csproj
source/Reloaded.Mod.Loader.IO/Config/ModConfig.cs
source/Reloaded.Mod.Loader.IO/ConfigReader.cs
source/Reloaded.Mod.Loader.IO/Reloaded.Mod.Loader.IO.csproj
source/Reloaded.Mod.Loader.IO/Services/ConfigServiceBase.cs
source/Reloaded.Mod.Loader.IO/Services/ModConfigService.cs
source/Reloaded.Mod.Loader.IO/Utility/IOEx.cs
source/Reloaded.Mod.Loader.IO/Utility/Parsers/BasicPeParser.cs

This adds support for reading mods in (nested) sub-directories and modifies the displayed name in the UI (limited to the `Configure Mods` and `Manage Mods` pages) with that of the directory tree, excluding the last folder that is often the mod id.
I prefer this a bit more since I am often downloading and updating mods manually, and not every mod author uses a naming convention that makes sense to me.
* This does change the base ConfigService, so applications will also listen to changes in the sub-directories. I don't think this is a big deal really but the adjusted watchers could be moved if needed.
* Updating the new mod properties right after reading the configurations.
* I had to override `AddItem` for this because otherwise it would mess up in the `Manage Mods` page when a mod got …

Support mod subdirectories

---

.github/workflows/DeployMkDocs.yml
.github/workflows/build-and-publish.yml
.github/workflows/reloaded-utils-server.yml
source/Mods/Reloaded.Utils.Server/Reloaded.Utils.Server.csproj
source/Reloaded.Mod.Loader.Server/Reloaded.Mod.Loader.Server.csproj
source/Reloaded.Mod.Template/Reloaded.Mod.Template.NuGet.csproj
source/Reloaded.Mod.Template/templates/configurable/.github/workflows/reloaded.yml
source/Reloaded.Mod.Template/templates/configurable/Reloaded.Mod.Template.csproj

Upgrade Reloaded.Mod.Template
- C# Lang 10 -> 12
- NET7.0 -> NET8.0
- Add Microsoft.NET.ILLink.Tasks as dependency for .NET 8 compatibility
- Bump Template version 1.6.2 -> 1.6.3
Upgrade GH Actions
- Upgrade all Microsoft actions to v4
- Upgrade other actions to latest stable releases

Updated: Reloaded.Mod.Template and GH Actions

---

.github/workflows/build-and-publish.yml
source/Publish.ps1
source/Reloaded.Mod.Installer/FodyWeavers.xml
source/Reloaded.Mod.Installer/Reloaded.Mod.Installer.csproj

This PR adds a single file, self contained distribution of setup.exe to make setup on Linux a bit easier.
(The EXE is unfortunately huge, WPF is not trimmable)
This allows for the installer to be used under Linux without needing to run
```
winetricks dotnet48
```
Or equivalent.

Added: Static Build of Setup.exe for Linux Use

---

source/Reloaded.Mod.Installer/MainWindowViewModel.cs
source/Reloaded.Mod.Installer/NativeMethods.txt
source/Reloaded.Mod.Installer/Reloaded.Mod.Installer.csproj
source/Reloaded.Mod.Installer/Utilities/IOEx.cs
source/Reloaded.Mod.Installer/Utilities/Native.cs
source/Reloaded.Mod.Installer/Utilities/ObservableObject.cs

This patch de-escalates the `Reloaded-II.exe` process started by `Setup.exe`. Doing this was surprisingly complex, but hopefully this works. In the case of error, I added a fallback that will start process normally.
Outside of that, I made a simple patch that will hopefully prevent data loss on re-installs:

Setup: Abort on Existing Directory & Don't Start Process as Admin

---

source/Reloaded.Mod.Launcher.Lib/Commands/Mod/DeleteModCommand.cs
source/Reloaded.Mod.Launcher.Lib/Static/Resources.cs
source/Reloaded.Mod.Launcher/Assets/Languages/en-GB.xaml

Resolves https://github.com/Reloaded-Project/Reloaded-II/issues/269
Only adds en-GB strings, translations needed for other langs.
I'm open to different description wording, I couldn't come up with a phrase I liked without changing OK and Cancel to Yes/No.
When using other languages it fallsback to en-GB, example:

Enhancement: Confirm dialog for Mod Delete

---

source/Reloaded.Mod.Installer.Lib/Settings.cs

Makes the Reloaded-II initial installation fallback to SysDriveRoot (commonly C:\) if OneDrive is detected in the path to the user's Desktop.
Resolves https://github.com/Reloaded-Project/Reloaded-II/issues/477

Enhancement: Fallback to SysDriveRoot on Install if OneDrive detected

---

source/Reloaded.Mod.Loader.Update/Dependency/Interfaces/RedistributableDependency.cs

Updates the akams link to v17 with 2022 names in `RedistributableDependency.cs`

Update: Link to 2022 C++ redists instead of 2019

---

source/Mods/Reloaded.Utils.Server/Reloaded.Utils.Server.csproj
source/Reloaded.Mod.Installer.Cli/Reloaded.Mod.Installer.Cli.csproj
source/Reloaded.Mod.Installer.DependencyInstaller/Reloaded.Mod.Installer.DependencyInstaller.csproj
source/Reloaded.Mod.Installer.Lib/Reloaded.Mod.Installer.Lib.csproj
source/Reloaded.Mod.Installer/Reloaded.Mod.Installer.csproj
source/Reloaded.Mod.Launcher.Lib/Reloaded.Mod.Launcher.Lib.csproj
source/Reloaded.Mod.Launcher/Reloaded.Mod.Launcher.csproj
source/Reloaded.Mod.Loader.Community/Reloaded.Mod.Loader.Community.csproj
source/Reloaded.Mod.Loader.IO/Reloaded.Mod.Loader.IO.csproj
source/Reloaded.Mod.Loader.Server/Reloaded.Mod.Loader.Server.csproj
source/Reloaded.Mod.Loader.Update.Packaging/Reloaded.Mod.Loader.Update.Packaging.csproj
source/Reloaded.Mod.Loader.Update/Reloaded.Mod.Loader.Update.csproj
source/Reloaded.Mod.Loader/Reloaded.Mod.Loader.csproj
source/Reloaded.Mod.Template/templates/configurable/Reloaded.Mod.Template.csproj
source/Tools/Reloaded.AutoIndexBuilder/Reloaded.AutoIndexBuilder.csproj
source/Tools/Reloaded.Publisher/Reloaded.Publisher.csproj

Makes this PR obsolete:
https://github.com/Reloaded-Project/Reloaded-II/pull/472
```
--Reloaded.Utils.Server--
Microsoft.NET.ILLink.Tasks 8.0.8 -> 8.0.11
--Reloaded.Mod.Installer.Cli--
DotNet.ReproducibleBuilds 1.1.1 -> 1.2.25
--Reloaded.Mod.Installer.DependencyInstaller--
DotNet.ReproducibleBuilds 1.1.1 -> 1.2.25
--Reloaded.Mod.Installer.Lib--
DotNet.ReproducibleBuilds 1.1.1 -> 1.2.25
PropertyChanged.Fody 3.4.1 -> 4.1.0
--Reloaded.Mod.Installer--
DotNet.ReproducibleBuilds 1.1.1 -> 1.2.25
PropertyChanged.Fody 3.4.1 -> 4.1.0
--Reloaded.Mod.Launcher.Lib--
DotNet.ReproducibleBuilds 1.1.1 -> 1.2.25
PropertyChanged.Fody 3.4.1 -> 4.1.0
--Reloaded.Mod.Launcher--
DotNet.ReproducibleBuilds 1.1.1 -> 1.2.25
gong-wpf-dragdrop 3.1.1 -> 3.2.1
PropertyChanged.Fody 3.4.1 -> 4.1.0 …
```

Chore: Update dependencies

---

source/Reloaded.Mod.Launcher/Pages/BaseSubpages/SettingsPage.xaml
source/Reloaded.Mod.Launcher/Reloaded.Mod.Launcher.csproj
source/Reloaded.Mod.Launcher/Theme/Halogen/Styles.xaml

Resolves https://github.com/Reloaded-Project/Reloaded-II/issues/500
* Increase brightness of the secondary type text 3c3c3c -> 7c7c7c; Effectively a brighter gray
* MouseOver for Checkbox content (text associated) and for the Reloaded Warning added for consistency

Default Color Adjustments and Consistency for Accessibility

---

source/Reloaded.Mod.Launcher.Lib/Commands/Application/AddApplicationCommand.cs
source/Reloaded.Mod.Launcher.Lib/Static/Resources.cs
source/Reloaded.Mod.Launcher/Assets/Languages/en-GB.xaml

Resolves https://github.com/Reloaded-Project/Reloaded-II/issues/503
Language TBD / feel free to change.
EN lang only; Translations needed eventually (presumably in a follow up sync etc)
It may be too wordy/technical.
I considered saying `game` instead of application, but the rest of Reloaded-II refers to added targets as applications.

Enhancement: AddApplication warns for OneDrive and non-ascii paths

---

source/Reloaded.Mod.Launcher.Lib/Static/Resources.cs
source/Reloaded.Mod.Launcher/App.xaml.cs
source/Reloaded.Mod.Launcher/Assets/Languages/en-GB.xaml

Resolves https://github.com/Reloaded-Project/Reloaded-II/issues/502
On boot, this appears if OneDrive or non-ascii chars are detected in the path Reloaded-II is contained in:
Clicking OK dismisses and the program continues as usual.
This will appear *every time* if detected.
I debated about introducing "ignore permanently", but ultimately the goal of this is to inform users and reduce possible issue reports relating to path issues, so I think its wise to permanently nag the user if these scenarios are detected.
--
For the first time user, this would appear and then the R-II Tutorial would appear at the same time if the detection occurs. They must complete or skip the tutorial before they can interact with the warning. After both are dismissed the main window loads.
I don't consider this …

Enhancement: Warn on R-II path in OneDrive/non-ascii on startup

---

source/Reloaded.Mod.Launcher/Controls/PropertyGridEx.cs
source/Reloaded.Mod.Launcher/Pages/Dialogs/ConfigureModDialog.xaml
source/Reloaded.Mod.Template/Reloaded.Mod.Template.NuGet.csproj
source/Reloaded.Mod.Template/templates/configurable/Config.cs

Uses the `DisplayAttribute`'s `Order` to set the `PropertyItem`'s existing `Priority` property, with a bit of a code to stop every mod's config order from shuffling.
Also added examples to the template.

Add support for ordering items in mod configs.

---

source/Reloaded.Mod.Launcher/Controls/PropertyGridEx.cs
source/Reloaded.Mod.Template/Reloaded.Mod.Template.NuGet.csproj
source/Reloaded.Mod.Template/templates/configurable/Config.cs

Adds support for named enum values in configs using `Display`'s `Name` property. Apparently, the `DisplayName` attribute doesn't support enum values, sadge.
Also, simplified the item ordering to use either the specified order or its default (`0`). I expected shuffling based on previous tests but those weren't using the built-in Priority.

Add support for named enum values in configs.

---

source/Reloaded.Mod.Launcher/Controls/PropertyGridEx.cs

The `DefaultValue` property stores integers as ints, which caused a crash if the target property was different integer type (byte, short, etc). Now runs `Convert.ChangeType` on the default value before setting it.

Fix crashes when resetting configs.

---

source/Reloaded.Mod.Template/Reloaded.Mod.Template.NuGet.csproj
source/Reloaded.Mod.Template/templates/configurable/Template/Startup.cs

The template doesn't set any `ConfigContext` when initialized through the loader. This sets the context with at least the `IApplicationConfig`. Not sure if the other properties are possible to fill, or even useful to.
For reference, I needed it for app specific configs.

Fix: Mod template ConfigContext not being set.

---

source/Reloaded.Mod.Launcher.Lib/Update.cs
source/Reloaded.Mod.Loader.Tests/Reloaded.Mod.Loader.Tests.csproj
source/Reloaded.Mod.Loader.Tests/Update/Providers/GameBanana/GameBananaDependencyResolverTests.cs
source/Reloaded.Mod.Loader.Update/Interfaces/IDependencyResolver.cs
source/Reloaded.Mod.Loader.Update/Providers/GameBanana/GameBananaDependencyResolver.cs
source/Reloaded.Mod.Loader.Update/Providers/GitHub/GitHubDependencyResolver.cs

For now we don't do anything with the errors, hope the IndexDependencyResolver picks up.
Later, we may do something more.

Added: Field to Store Exceptions During Failures in Dependency Resoution

---

source/Reloaded.Mod.Launcher.Lib/Utility/AsiLoaderDeployer.cs

* Flips to use the list supplied order rather than first match from the PEHeader
* Re-orders the list to be least intrusive and by most compatible. version.dll is number 1 check because it only checks platform. DSound may have issues on Linux for example, hence the change.

Launcher.Lib: Use multiplatform compatible target AsiLoaderDLL by default
